baseURL = 'https://yota.uba.be'
languageCode = 'en-us'
title = 'YOTA Belgium'


[params]
  Title = "YOTA Belgium"
  description = "UBA YOTA"
  dateFormat = "2 Jan 2006"

[taxonomies]
  category = "categories"
  author = "authors"